// <auto-generated />
using FoodSaverApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FoodSaverAPI.Migrations
{
    [DbContext(typeof(FoodSaverApiContext))]
    [Migration("20191106050552_Update2")]
    partial class Update2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("FoodSaverApi.Models.Ingredient", b =>
                {
                    b.Property<int>("IngredientId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("IngredientName");

                    b.Property<decimal>("IngredientPrice");

                    b.Property<int>("IngredientQuantity");

                    b.Property<string>("IngredientSubstitution");

                    b.HasKey("IngredientId");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            IngredientId = 1,
                            IngredientName = "lb wheat spaghetti",
                            IngredientPrice = 1.20m,
                            IngredientQuantity = 2,
                            IngredientSubstitution = "lb wheat pasta any shape"
                        },
                        new
                        {
                            IngredientId = 2,
                            IngredientName = "28oz can diced tomatoes",
                            IngredientPrice = 1.10m,
                            IngredientQuantity = 1,
                            IngredientSubstitution = "double tomato sauce quantity"
                        },
                        new
                        {
                            IngredientId = 3,
                            IngredientName = "16oz can tomato sauce",
                            IngredientPrice = 0.60m,
                            IngredientQuantity = 1,
                            IngredientSubstitution = "jar tomato-basil/marinara pasta sauce"
                        },
                        new
                        {
                            IngredientId = 4,
                            IngredientName = "large onion",
                            IngredientPrice = 0.70m,
                            IngredientQuantity = 1,
                            IngredientSubstitution = "onion powder, diced vegetable"
                        },
                        new
                        {
                            IngredientId = 5,
                            IngredientName = "cloves garlic",
                            IngredientPrice = 0.50m,
                            IngredientQuantity = 4,
                            IngredientSubstitution = "garlic powder, italian seasoning"
                        },
                        new
                        {
                            IngredientId = 6,
                            IngredientName = "lb ground beef chuck 80/20",
                            IngredientPrice = 3.00m,
                            IngredientQuantity = 1,
                            IngredientSubstitution = "lb fresh or frozen ground beef/turkey/lean pork."
                        },
                        new
                        {
                            IngredientId = 7,
                            IngredientName = "7-9oz box white cheddar macaroni and cheese",
                            IngredientPrice = 0.75m,
                            IngredientQuantity = 1,
                            IngredientSubstitution = "any flavor boxed macaroni and cheese"
                        },
                        new
                        {
                            IngredientId = 8,
                            IngredientName = "12oz frozen broccolli florets",
                            IngredientPrice = 1.00m,
                            IngredientQuantity = 1,
                            IngredientSubstitution = "12oz steam-in-bag frozen vegetable/vegetable mixes"
                        },
                        new
                        {
                            IngredientId = 9,
                            IngredientName = "7-9oz box white cheddar macaroni and cheese",
                            IngredientPrice = 0.75m,
                            IngredientQuantity = 1,
                            IngredientSubstitution = "any 7-9oz boxed macaroni and cheese"
                        },
                        new
                        {
                            IngredientId = 10,
                            IngredientName = "5oz can chunk light tuna in water",
                            IngredientPrice = 0.75m,
                            IngredientQuantity = 1,
                            IngredientSubstitution = "5oz can tuna of any variety"
                        });
                });

            modelBuilder.Entity("FoodSaverApi.Models.IngredientRecipe", b =>
                {
                    b.Property<int>("IngredientRecipeId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("IngredientId");

                    b.Property<int>("RecipeId");

                    b.HasKey("IngredientRecipeId");

                    b.HasIndex("IngredientId");

                    b.HasIndex("RecipeId");

                    b.ToTable("IngredientRecipes");

                    b.HasData(
                        new
                        {
                            IngredientRecipeId = 1,
                            IngredientId = 1,
                            RecipeId = 1
                        },
                        new
                        {
                            IngredientRecipeId = 2,
                            IngredientId = 2,
                            RecipeId = 1
                        },
                        new
                        {
                            IngredientRecipeId = 3,
                            IngredientId = 3,
                            RecipeId = 1
                        },
                        new
                        {
                            IngredientRecipeId = 4,
                            IngredientId = 4,
                            RecipeId = 1
                        },
                        new
                        {
                            IngredientRecipeId = 5,
                            IngredientId = 5,
                            RecipeId = 1
                        },
                        new
                        {
                            IngredientRecipeId = 6,
                            IngredientId = 6,
                            RecipeId = 1
                        },
                        new
                        {
                            IngredientRecipeId = 7,
                            IngredientId = 7,
                            RecipeId = 2
                        },
                        new
                        {
                            IngredientRecipeId = 8,
                            IngredientId = 8,
                            RecipeId = 2
                        },
                        new
                        {
                            IngredientRecipeId = 9,
                            IngredientId = 9,
                            RecipeId = 2
                        },
                        new
                        {
                            IngredientRecipeId = 10,
                            IngredientId = 10,
                            RecipeId = 2
                        });
                });

            modelBuilder.Entity("FoodSaverApi.Models.Recipe", b =>
                {
                    b.Property<int>("RecipeId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Directions");

                    b.Property<string>("NutritionInfo");

                    b.Property<decimal>("PricePerServing");

                    b.Property<string>("RecipeName");

                    b.Property<string>("RecipeTips");

                    b.HasKey("RecipeId");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            RecipeId = 1,
                            Directions = "1) Combine ground beef, onion, and garlic. Cook and stir until meat is brown and vegetables are tender. Drain grease.",
                            NutritionInfo = "fiber, vitamins, minerals, hella flavor ",
                            PricePerServing = 1.00m,
                            RecipeName = "Spaghetti and Beef Marinara",
                            RecipeTips = "How to turn this into leftovers for lunch. save the leftover half of your onion for other crap. How to store info. What you can add if you have it."
                        },
                        new
                        {
                            RecipeId = 2,
                            Directions = "1) Steam brocolli in microwave or in a covered pot with steamer on the stovetop. 2) Open and strain canned tuna 2) Boil macaroni according to package instructions, strain pasta, and combine with steamed brocolli, packaged cheese, extra cheese, milk, tuna, and salt and pepper to taste. Return to microwave or pot on stovetop and heat on low until cheese is melted.",
                            NutritionInfo = " ",
                            PricePerServing = 2.25m,
                            RecipeName = "Tuna Mac and Cheese",
                            RecipeTips = " "
                        });
                });

            modelBuilder.Entity("FoodSaverApi.Models.IngredientRecipe", b =>
                {
                    b.HasOne("FoodSaverApi.Models.Ingredient", "Ingredient")
                        .WithMany("Recipes")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("FoodSaverApi.Models.Recipe", "Recipe")
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
